#server:
#  port: 8080
#
#spring:
#  application:
#    name: order_management
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order_management
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update   # use validate/none in prod
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true